### PR TITLE
Sponsorship Page

### PR DESCRIPTION
**Pull request by Forsyth-Creations**

### CODE REVIEW

**Comment by Forsyth-Creations** [comment]
Screenshot from 2023-10-24 00-46-16

**Comment by Forsyth-Creations** [comment]
Screenshot from 2023-10-24 00-46-16

**Comment by Forsyth-Creations** [comment]
image

**Comment by Forsyth-Creations** [comment]
image

**Review by jiviteshkuk26 — APPROVED** [review]

**Pull request merged**
