### PR TITLE
add 8-bit computer project

### PR DESCRIPTION
**Pull request by ethanjamesauto**

### CODE REVIEW

**Comment by Forsyth-Creations** [comment]
We have two 8 bit computer projects now, huh? As long as you checked that the repo images show up in the dev environment, I'm game to send this PR

**Comment by ethanjamesauto** [comment]
I apologize, but I don't have the dev environment set up. Could you or another webdev please test this branch? If not, I could try to set it up, but I'm no web developer.

**Comment by Forsyth-Creations** [comment]
image


Seems to work to me

**Review by Forsyth-Creations — APPROVED** [review]
Looks good to me. Send it

**Pull request merged**
